//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 10:08:50 PM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.neslonaitsknarf.com/xml/book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_neslonaitsknarf_com.xml.book;
